# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f60928996690c44e7af436fffb0045fb34e9f471b6b886b7dca8946dcead8c9ba39797405876797279786af1a7abcb2671c419be68d5047c377525693cc277a

test:
  secret_key_base: a746554c6fbe366366c603d2026b65dbd2b52d10f59ff747e85101b86bb491b77b79cf97462c671794114d973b8e02fa5dbf49b9925ab72efbf4573768781e43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
